name: R-CMD-check (disabled)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - name: Restore renv and install deps
        run: |
          R -q -e "renv::restore(prompt = FALSE)"
          R -q -e "source('dependencies.R'); install.packages('pak'); pak::pkg_install(project_dependencies())"
      - name: Run tests
        run: R -q -e "testthat::test_dir('tests/testthat', reporter = 'summary')"
      - name: Render docs (optional)
        run: |
          pipx install quarto || true
          quarto --version || true
          quarto render docs/
        continue-on-error: true

